---
# tasks file for dhcp
- name: Package
  ansible.builtin.package:
    name: "{{ dhcp_packages }}"
  tags:
    - dhcp
    - package

- name: Service facts
  ansible.builtin.service_facts:
  tags:
    - dhcp
    - facts

- name: Configuration
  when:
    - "'isc-dhcp-server.service' in services"
  block:
    - name: Interfaces
      ansible.builtin.lineinfile:
        dest: '{{ dhcp_default_file }}'
        regexp: '^INTERFACESv4=".*"'
        line:
          'INTERFACESv4="{{ dhcp_interfaces |
          default(ansible_default_ipv4.interface) }}"'
      notify:
        - dhcpd restart
      tags:
        - dhcp
        - interfaces

    - name: DHCPDv4_CONF
      ansible.builtin.lineinfile:
        dest: '{{ dhcp_default_file }}'
        regexp: '.*DHCPDv4_CONF=.*'
        line: "DHCPDv4_CONF={{ dhcp_dhcpd4_config_file }}"
      when:
        - dhcp_dhcpd4_config_file is defined
      notify:
        - dhcpd restart
      tags:
        - dhcp
        - v4conf

    - name: Config
      ansible.builtin.template:
        src: 'dhcpd-{{ dhcp_role }}.conf.j2'
        dest: "{{ dhcp_dhcpd4_config_file | default('/etc/dhcp/dhcpd.conf') }}"
        mode: 0644
      notify:
        - dhcpd restart
      tags:
        - dhcp
        - config

    - name: Shared config
      ansible.builtin.template:
        src: 'dhcpd-shared.conf.j2'
        dest: "{{ dhcp_failover_shared_config_file }}"
        mode: 0644
      notify:
        - dhcpd restart
      when:
        - dhcp_role in [ 'primary', 'secondary' ]
      tags:
        - dhcp
        - config
        - shared
